# ---
# n8n MAIN (Editor/API). Disable production webhooks so only webhook pods handle them.
# ---
apiVersion: v1
kind: Service
metadata:
  name: n8n-main
  namespace: ns-n8n
spec:
  type: ClusterIP
  selector:
    app: n8n-main
  ports:
    - name: http
      port: 5678
      targetPort: 5678

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: n8n-main-np
#  namespace: ns-n8n
#spec:
#  type: NodePort
#  selector:
#    app: n8n-main
#  ports:
#    - name: http
#      nodePort: 32678
#      port: 5678
#      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-main
  namespace: ns-n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-main
  template:
    metadata:
      labels:
        app: n8n-main
    spec:
      containers:
        - name: n8n
          image: registry.easesaas.com/myron/n8nio-n8n:1.109.2
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          envFrom:
            - configMapRef: { name: n8n-config }
            - secretRef: { name: n8n-secrets }
          env:
            - name: N8N_DISABLE_PRODUCTION_MAIN_PROCESS
              value: "true"
            - name: N8N_LOG_LEVEL
              value: "debug"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "false"
          ports:
            - containerPort: 5678
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits:   { cpu: "1000m", memory: "1Gi" }
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: 5678
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 30
            periodSeconds: 20