# ---
# n8n WEBHOOK processors (scale this for high concurrency)
# ---
apiVersion: v1
kind: Service
metadata:
  name: n8n-webhook
  namespace: ns-n8n
spec:
  type: ClusterIP
  selector:
    app: n8n-webhook
  ports:
    - name: http
      port: 5678
      targetPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-webhook-np
  namespace: ns-n8n
spec:
  type: NodePort
  selector:
    app: n8n-webhook
  ports:
    - name: http
      port: 5678
      targetPort: 5678
      nodePort: 32679
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-webhook
  namespace: ns-n8n
spec:
  replicas: 2  # adjust to your traffic
  selector:
    matchLabels:
      app: n8n-webhook
  template:
    metadata:
      labels:
        app: n8n-webhook
    spec:
      containers:
        - name: n8n
          image: registry.easesaas.com/myron/n8nio-n8n:1.109.2
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command: ["n8n","webhook"]
          envFrom:
            - configMapRef: { name: n8n-config }
            - secretRef: { name: n8n-secrets }
          ports:
            - containerPort: 5678
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits:   { cpu: "1000m", memory: "1Gi" }
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: 5678
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 20
            periodSeconds: 10